### ISSUE TITLE
Define a structure for configuring JBoss Instances

### ISSUE THREAD

**Issue by sabre1041** [redhat-cop/jboss_eap#54]
Allow for a structure to be provided to define the configuration of JBoss instances

Something similar to the following

```
jboss_instances:
  - name: jboss
    port_offset: 0
    jboss_resources:
        - jboss_resource:
            name: "/subsystem=datasources/data-source=DemoDS"
            state: present
            attributes:
              driver-name: h2
              connection-url: "jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
              jndi-name: "java:jboss/datasources/DemoDS"
              user-name: sa
              password: sa
              min-pool-size: 20
              max-pool-size: 40
  - name: jboss2
     port_offset: 100


```
